application:
  server:
    url: http://pogoda.atpm-air.ru/data.aspx


spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: sa
    password:

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: update